global using Krita.Core.Settings;
global using Krita.Web.Configurations;
global using Microsoft.AspNetCore.Mvc;
global using Krita.Core.Helpers;
global using Krita.Core.Interfaces;
global using Krita.Data.Repositories;
global using Krita.Data;
global using Krita.Core.Dto.Usuario;
global using Krita.Core.Models;
